import './src/layouts/0_page/page.js'
import './src/layouts/1_header/header.js'
import './src/layouts/2_intro/intro.js'
import './src/layouts/3_slider/slider.js'
import './src/layouts/4_info/info.js'
import './src/layouts/5_footer/footer.js'
import './src/layouts/5_footer/footer.js'